Name: Security
Dir: security
Distros: openshift-enterprise,openshift-webscale,openshift-origin,openshift-aro
Topics:
- Name: Container security
  Dir: container_security
  Topics:
  - Name: Understanding container security
    File: security-understanding
  - Name: Understanding host and VM security
    File: security-hosts-vms
  - Name: Hardening Red Hat Enterprise Linux CoreOS
    File: security-hardening
    Distros: openshift-enterprise,openshift-webscale,openshift-aro
  - Name: Hardening Fedora CoreOS
    File: security-hardening
    Distros: openshift-origin
  - Name: Understanding compliance
    File: security-compliance
  - Name: Securing container content
    File: security-container-content
  - Name: Using container registries securely
    File: security-registries
  - Name: Securing the build process
    File: security-build
  - Name: Deploying containers
    File: security-deploy
  - Name: Securing the container platform
    File: security-platform
  - Name: Securing networks
    File: security-network
  - Name: Securing attached storage
    File: security-storage
  - Name: Monitoring cluster events and logs
    File: security-monitoring
- Name: Configuring certificates
  Dir: certificates
  Distros: openshift-enterprise,openshift-webscale,openshift-origin
  Topics:
  - Name: Replacing the default ingress certificate
    File: replacing-default-ingress-certificate
  - Name: Adding API server certificates
    File: api-server
  - Name: Securing service traffic using service serving certificates
    File: service-serving-certificate
- Name: Certificate types and descriptions
  File: certificate-types-descriptions
  Distros: openshift-enterprise,openshift-webscale,openshift-origin
- Name: Allowing JavaScript-based access to the API server from additional hosts
  File: allowing-javascript-access-api-server
  Distros: openshift-enterprise,openshift-webscale,openshift-origin
- Name: Encrypting etcd data
  File: encrypting-etcd
  Distros: openshift-enterprise,openshift-webscale,openshift-origin
- Name: Scanning pods for vulnerabilities
  File: pod-vulnerability-scan
  Distros: openshift-enterprise,openshift-webscale,openshift-origin
