Name: Service Mesh
Dir: service_mesh
Distros: openshift-enterprise,openshift-webscale
Topics:
- Name: Service Mesh release notes
  File: servicemesh-release-notes
- Name: Service Mesh architecture
  Dir: service_mesh_arch
  Topics:
  - Name: Understanding Service Mesh
    File: understanding-ossm
  - Name: Understanding Kiali
    File: ossm-kiali
  - Name: Understanding Jaeger
    File: ossm-jaeger
  - Name: Comparing Service Mesh and Istio
    File: ossm-vs-community
- Name: Service Mesh installation
  Dir: service_mesh_install
  Topics:
  - Name: Preparing to install Service Mesh
    File: preparing-ossm-installation
  - Name: Installing Service Mesh
    File: installing-ossm
  - Name: Customizing the installation
    File: customizing-installation-ossm
  - Name: Updating Service Mesh
    File: updating-ossm
  - Name: Removing Service Mesh
    File: removing-ossm
- Name: Day Two
  Dir: service_mesh_day_two
  Topics:
  - Name: Deploying applications on Service Mesh
    File: prepare-to-deploy-applications-ossm
  - Name: Configuring Jaeger
    File: configuring-jaeger
  - Name: Example application
    File: ossm-example-bookinfo
  - Name: Distributed tracing tutorial
    File: ossm-tutorial-jaeger-tracing
  - Name: Automatic route creation
    File: ossm-auto-route
- Name: Service Mesh user guide
  Dir: service_mesh_user_guide
  Topics:
  - Name: Traffic management
    File: ossm-traffic-manage
  - Name: Data visualization and observability
    File: ossm-observability
  - Name: Security
    File: ossm-security
- Name: Support
  Dir: service_mesh_support
  Topics:
  - Name: Collecting Service Mesh data for support
    File: ossm-collecting-ossm-data
- Name: 3scale adapter
  Dir: threescale_adapter
  Topics:
  - Name: Using the 3scale Istio adapter
    File: threescale-adapter

